name: Deploy Project-V1
on: push
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code From Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ....." 